version: "2.17.3"

services:
  ui:
    image: dien2khust/emailui:0.1
    restart: on-failure
    ports:
      - 2804:8080
  backend:
    image: dien2khust/emailspamer:0.0.0.1
    restart: on-failure
    ports:
      - 1234:80
